language: csharp
mono:
- latest
install:
- nuget restore
script:
- ./.ci.sh
env:
  secure: BV2FU8wMq5pjb+Qoz3JDLXA3FvtaAvnMqUUvlCMPVFMIKrlm9DHvmr9vUrsXDvBOkQ0ozw00Ijv6TTx7U8jjt2JCqbMERXf5qMhJonlmqphnRfPbqQkuD90ERCQXaXDvxhXDog308zDVaQOsAshUMmcSk92k7he1nofSkGbJjsOWAjERun1mCEAes0Uw21kNho/GS9/xIBCz6p7H0ZqYUN2Pr/vdk0uOmi+cTeWrAqyF0Ba1EnF2CrYsZp25Ef5iYR9BBvRr7WK2w96K6vg8xZum9fJME75iAKPborV2IrtQ9R7kxD2RD03pyqo0NOEpy6a4X/fw1+Tc0BdqHv3TysB/3rPf8gez4QYy3xe9+z4yQrrzhchSf9wE9kjuM5JvdjKf40cGwO/GFIjPqnIwaCOn5yAsnUN9kU+eUUzefVum3zIDanlsKNLdvoYjfK8mxIQmID+4N1EZL3WXE5SDkIgFNk+b4Xp51RvK6h6oeSWQwb555om9SRTFlc9FWrZM+zns3YbwTgmEXRkqcT44xga2AQDhzH4g7ro+2IKWxVi/08+hSUQuZg6kZBVr+JhMY1sHDmwXFbGYSI8UHzxQ54SRATO+aIigZXC8ZwSojITSksiPGniIqcKJeBfDPkELbcTakD62CCmY+fbefC7GWWE8iWVrTo5DKPpMDzOl0uo=
